server:
  port: 8888

spring:
  application:
    name: GATEWAY-SERVCIE
    gateway:
      discovery:
        enabled: true
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
